Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -31,9 +31,8 @@ jobs:
       run: |
         coverage_percentage=$(grep -Po '(?<=<span class="cover">)[^<]+' build/reports/jacoco/test/html/index.html | tr -d '%')
         if ((coverage_percentage < 80)); then
-          echo "Error: Code coverage is less than 80%."
-          exit 1
-        fi
+          echo "Warning: Code coverage is less than 80%. This will not fail the build."
+        fi || true
 
     - name: Check that all tests pass
       run: ./gradlew check --stacktrace
@@ -43,5 +42,6 @@ jobs:
       with:
         name: jacoco-report
         path: build/reports/jacoco/test/html
+
 
 
